### ISSUE TITLE
Move cached_revision from Downward lab to lab

### ISSUE THREAD

**Issue by thomaskeller79** [aibasel/lab#79]
Other solvers than Fast Downward could also benefit from the caching of revisions that is implemented in downward/cached_revision.py. A quick look over the code shows only very few Fast Downward specific code in the file:

- the excluded dirs in line 177
- location and name of the build script
- some temporary filenames ("downward.tgz") and some strings ("get_planner_resource_name")
- binary names in _cleanup (and unnecessary files)

I could copy this file and adjust it for usage with Prost (which already does many things similar to Fast Downward), but it doesn't seem much harder to include a generalized version in (non-Fast Downward) lab. If you are interested I can have a look at this.

**Comment by jendrikseipp** [comment]
Sounds like a good idea, go ahead!

**Comment by gfrances** [comment]
+1 :-)

**Comment by jendrikseipp** [comment]
This has been merged a while ago.
